// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Z4AJFUATXr_EwjpzELr2f0rsW6pCAIs',
    appId: '1:240729433331:web:f31fda75152a3648104386',
    messagingSenderId: '240729433331',
    projectId: 'hydroponicsproject-29703',
    authDomain: 'hydroponicsproject-29703.firebaseapp.com',
    databaseURL: 'https://hydroponicsproject-29703-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroponicsproject-29703.appspot.com',
    measurementId: 'G-LS8Z5GTMJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUyvDJEFxCXQmZ1kiDykIxRjGmo2V2kq0',
    appId: '1:240729433331:android:fa9409957dda2bbf104386',
    messagingSenderId: '240729433331',
    projectId: 'hydroponicsproject-29703',
    databaseURL: 'https://hydroponicsproject-29703-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroponicsproject-29703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgzK4Xmka8Am77ESdavAZp6RiZzPyOCYA',
    appId: '1:240729433331:ios:e045312a5ffc4199104386',
    messagingSenderId: '240729433331',
    projectId: 'hydroponicsproject-29703',
    databaseURL: 'https://hydroponicsproject-29703-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroponicsproject-29703.appspot.com',
    iosBundleId: 'com.example.nonghidro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgzK4Xmka8Am77ESdavAZp6RiZzPyOCYA',
    appId: '1:240729433331:ios:e045312a5ffc4199104386',
    messagingSenderId: '240729433331',
    projectId: 'hydroponicsproject-29703',
    databaseURL: 'https://hydroponicsproject-29703-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroponicsproject-29703.appspot.com',
    iosBundleId: 'com.example.nonghidro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Z4AJFUATXr_EwjpzELr2f0rsW6pCAIs',
    appId: '1:240729433331:web:0e10d7a477ab4e0f104386',
    messagingSenderId: '240729433331',
    projectId: 'hydroponicsproject-29703',
    authDomain: 'hydroponicsproject-29703.firebaseapp.com',
    databaseURL: 'https://hydroponicsproject-29703-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroponicsproject-29703.appspot.com',
    measurementId: 'G-7CP90V6QD6',
  );
}
